---
- hosts: {{host_vars}}
  collections:
    - kubernetes.core
  tasks:
  - name: Deploy NodeJS-App
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Deployement
        metadata:
          name: "sample-app"
          namespace: default
          labels:
            app: sample-app
        spec:
          containers:
          - name: sample-app-nodejs
            image: menhkte.jfrog.io/default-docker/nodejs-sample-app:latest
            imagePullPolicy: IfNotPresent