---
- name: Undeploy Sample-App-NodeJS
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Deployment
    name: sample-app-nodejs
    namespace: sample-app

- name: Undeploy Sample-App-NodeJS Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: sample-app-nodejs-svc
    namespace: sample-app